return {
    {text = "Piece by piece", time = 19},
    {text = "You're leaving me in pieces on display", time = 21},
    {text = "for good while I'm fine and understood", time = 23},
    {text = "As I rattle my cell", time = 26},
    {text = "and recomputing molecules", time = 27},
    {text = "in prison bars", time = 29},
    {text = "Shot at my foot and not the stars", time = 30},
    {text = "OH!", time = 32},
    {text = "Ain't that a shame?", time = 33},
    {text = "My illness, a game?", time = 34},
    {text = "You've set yourself as queen and me as the pawn", time = 35},
    {text = "A move to the right", time = 38},
    {text = "and you're out of sight", time = 40},
    {text = "well, isn't that a pain you're finally gone!", time = 42},
    {text = "(oooh my god!)", time = 45},
    {text = "(Yay!)", time = 46},
    {text = "(music)", time = 47},
    {text = "Recomputing, couting the hours", time = 60},
    {text = "by their watching, waiting for years", time = 61},
    {text = "while they're begging tearfully", time = 62},
    {text = "What's the point?", time = 63},
    {text = "Am I really crying, shedding,", time = 64},
    {text = "letting somebody, anybody, use me for a utility?", time = 65},
    {text = "Utilizing, realizing god made me for a shameful purpose", time = 66},
    {text = "worthless, notice why", time = 69},
    {text = "Oh, why am I still alive?", time =  70},
    {text = "Could it be that life isn't worth the stife anyway?", time = 71},
    {text = "Oh my, what a sight!", time = 72},
    {text = "You've put up a fight!", time = 74},
    {text = "You've set yourself upright to be quite the show!", time = 75},
    {text = "A move to the left", time = 79},
    {text = "You're all out of help, well, isn't it a pain you reap what you sow!", time = 80},
    {text ="(oooh my god!)", time = 85},
    {text = "(recomputing)\n(piece by piece)\n(ain't that a shame?)", time = 88},
    {text = "(counting the hours by their watching)\n(You're leaving me in pieces)\n(My illness a game?)", time = 89},
    {text = "(waiting for years)\n(You've set yourself as queen and me as the pawn)\n(on display, for good)", time = 90},
    {text = "(while they're begging tearfully)\n(while I'm fine and understood)", time = 91},
    {text = "(What's the point? Am I really crying, shedding)", time = 92},
    {text = "(letting somebody, anybody, use me for a utility)", time = 93},
    {text = "(As I rattle my cell)\n(A move to the right)", time = 94},
    {text = "(and recomputing molecules)\n(and you're out of help!)\n(god made me for a shameful purpose)", time = 95},
    {text = "(in prison bars)\n(well, isn't that a pain you're finally gone!)\n(worthless, notice why)", time = 97},
    {text = "(Shot at my foot and not the stars!)\n(oh why am I still alive? Could it be that life isn't worth-)", time = 98},
    {text = "OH!", time = 100}
}